// Datos del pensum — Licenciatura en Literatura y Lengua Castellana
// Extraídos del Plan de Estudios (PDF oficial). Cada curso tiene código,
// nombre y créditos académicos. El total de créditos obligatorios (179)
// se usa para calcular el progreso general de la carrera.

const PENSUM = {
  totalCreditos: 179,
  semestres: [
    {
      numero: 1,
      creditos: 18,
      cursos: [
        { codigo: "2094101", nombre: "Práctica Pedagógica I", creditos: 3 },
        { codigo: "2094102", nombre: "Introducción a la literatura", creditos: 3 },
        { codigo: "2094103", nombre: "Taller de producción e interpretación textual", creditos: 3 },
        { codigo: "2094104", nombre: "Introducción a los estudios del lenguaje", creditos: 3 },
        { codigo: "2059004", nombre: "Historia, imágenes y concepciones del maestro", creditos: 3 },
        { codigo: "2059007", nombre: "Didácticas, saberes y evaluación", creditos: 3 },
      ],
    },
    {
      numero: 2,
      creditos: 18,
      cursos: [
        { codigo: "2094201", nombre: "Práctica pedagógica II", creditos: 3 },
        { codigo: "2094202", nombre: "Teorías Literarias I", creditos: 3 },
        { codigo: "2094203", nombre: "Fonética y fonología", creditos: 3 },
        { codigo: "2094304", nombre: "Morfología", creditos: 3 },
        { codigo: "2059002", nombre: "Sujetos en el acto educativo", creditos: 3 },
        { codigo: "2059008", nombre: "Cognición, cultura y aprendizaje", creditos: 3 },
      ],
    },
    {
      numero: 3,
      creditos: 17,
      cursos: [
        { codigo: "2094301", nombre: "Práctica Pedagógica III", creditos: 3 },
        { codigo: "2094302", nombre: "Teorías literarias II", creditos: 3 },
        { codigo: "2094303", nombre: "Literaturas griega y latina", creditos: 3 },
        { codigo: "2094404", nombre: "Sintaxis", creditos: 3 },
        { codigo: "2059001", nombre: "Educación Popular", creditos: 3 },
        { codigo: "9120101", nombre: "English 1", creditos: 2 },
      ],
    },
    {
      numero: 4,
      creditos: 18,
      cursos: [
        { codigo: "2094401", nombre: "Práctica Pedagógica IV", creditos: 4 },
        { codigo: "2094402", nombre: "Poesía", creditos: 3 },
        { codigo: "2094403", nombre: "Dramaturgia y teatro", creditos: 3 },
        { codigo: "2094204", nombre: "Historia de la Lengua", creditos: 3 },
        { codigo: "2059005", nombre: "Teorías curriculares y contextos educativos", creditos: 3 },
        { codigo: "9120102", nombre: "English 2", creditos: 2 },
      ],
    },
    {
      numero: 5,
      creditos: 19,
      cursos: [
        { codigo: "2094501", nombre: "Práctica Pedagógica V", creditos: 5 },
        { codigo: "2094502", nombre: "Ensayo", creditos: 3 },
        { codigo: "2094503", nombre: "Semántica", creditos: 3 },
        { codigo: "2094504", nombre: "Proyecto de Psicolingüística", creditos: 3 },
        { codigo: "2059003", nombre: "Tradiciones y paradigmas en pedagogía", creditos: 3 },
        { codigo: "9120103", nombre: "English 3", creditos: 2 },
      ],
    },
    {
      numero: 6,
      creditos: 19,
      cursos: [
        { codigo: "2094601", nombre: "Práctica Pedagógica VI", creditos: 5 },
        { codigo: "2094602", nombre: "Literatura española", creditos: 3 },
        { codigo: "2094603", nombre: "Seminario temático en literatura", creditos: 3 },
        { codigo: "2094604", nombre: "Proyecto de Pragmática", creditos: 3 },
        { codigo: "2059006", nombre: "Política pública y legislación educativa", creditos: 3 },
        { codigo: "9120104", nombre: "English 4", creditos: 2 },
      ],
    },
    {
      numero: 7,
      creditos: 19,
      cursos: [
        { codigo: "2094701", nombre: "Práctica Pedagógica VII", creditos: 5 },
        { codigo: "2094702", nombre: "Literatura europea", creditos: 3 },
        { codigo: "2094703", nombre: "Proyecto de sociolingüística", creditos: 3 },
        { codigo: "2059015", nombre: "Educación e inclusión", creditos: 3 },
        { codigo: "2022041", nombre: "Introducción al razonamiento abstracto y pensamiento matemático", creditos: 3 },
        { codigo: "9120105", nombre: "English 5", creditos: 2 },
      ],
    },
    {
      numero: 8,
      creditos: 19,
      cursos: [
        { codigo: "2094801", nombre: "Práctica Pedagógica VIII", creditos: 8 },
        { codigo: "2094802", nombre: "Seminario de investigación literaria", creditos: 3 },
        { codigo: "2094803", nombre: "Proyecto de semiótica de la cultura", creditos: 3 },
        { codigo: "ELEC-8-1", nombre: "Electiva I", creditos: 3 },
        { codigo: "2059014", nombre: "Formación ciudadana", creditos: 2 },
      ],
    },
    {
      numero: 9,
      creditos: 17,
      cursos: [
        { codigo: "2094901", nombre: "Práctica Pedagógica IX", creditos: 8 },
        { codigo: "2094902", nombre: "Literatura latinoamericana", creditos: 3 },
        { codigo: "2094903", nombre: "Seminario de investigación en lingüística", creditos: 3 },
        { codigo: "ELEC-9-1", nombre: "Electiva II", creditos: 3 },
      ],
    },
    {
      numero: 10,
      creditos: 15,
      cursos: [
        { codigo: "2094010", nombre: "Práctica Pedagógica X: Trabajo de grado", creditos: 6 },
        { codigo: "2094020", nombre: "Literatura colombiana", creditos: 3 },
        { codigo: "ELEC-10-1", nombre: "Electiva III", creditos: 3 },
        { codigo: "ELEC-10-2", nombre: "Electiva IV", creditos: 3 },
      ],
    },
  ],

  // Banco de materias electivas (campo de saber pedagógico y disciplinar).
  // Se muestran aparte como referencia/selección personal: no suman al
  // total de 179 créditos porque ya están contados como "Electiva I-IV"
  // dentro de los semestres VIII, IX y X.
  electivas: [
    { codigo: "2022001", nombre: "Educación y sociedad" },
    { codigo: "2022002", nombre: "Ética y educación política" },
    { codigo: "2022003", nombre: "Artes, estética y educación" },
    { codigo: "2022005", nombre: "Educación socioemocional" },
    { codigo: "2022006", nombre: "Educación y salud" },
    { codigo: "2022007", nombre: "Educación en ambientes no convencionales" },
    { codigo: "2022008", nombre: "Educación y cine" },
    { codigo: "2022009", nombre: "Pedagogía del cuerpo" },
    { codigo: "2022010", nombre: "Educación ambiental y sociedad" },
    { codigo: "2022011", nombre: "Educación rural" },
    { codigo: "2022012", nombre: "Educación, género y sexualidad" },
    { codigo: "2022013", nombre: "Estudios afro en educación" },
    { codigo: "2022014", nombre: "Problemas contemporáneos en educación" },
    { codigo: "2022015", nombre: "Infancias y culturas juveniles" },
    { codigo: "2022016", nombre: "Teorías de la formación" },
    { codigo: "2022017", nombre: "Pedagogías contemporáneas" },
    { codigo: "2022018", nombre: "Pedagogías críticas" },
    { codigo: "2022019", nombre: "Pedagogías ancestrales" },
    { codigo: "2022020", nombre: "Grandes pedagogos" },
    { codigo: "2022021", nombre: "Formación en investigación educativa y pedagógica I" },
    { codigo: "2022022", nombre: "Formación en investigación educativa y pedagógica II" },
    { codigo: "2022023", nombre: "Gestión y cultura escolar" },
    { codigo: "2022024", nombre: "Construcción, diseño y evaluación curricular" },
    { codigo: "2022025", nombre: "Economía y educación" },
    { codigo: "2022026", nombre: "Diseño, gestión y evaluación de instrumentos de planeación educativa" },
    { codigo: "2022027", nombre: "Evaluación de los aprendizajes" },
    { codigo: "2022028", nombre: "Cibercultura y mediación pedagógica" },
    { codigo: "2022029", nombre: "Creatividad e innovación en educación" },
    { codigo: "2022030", nombre: "Formación para el emprendimiento" },
    { codigo: "2022031", nombre: "Educación de sordos, lengua y comunidad" },
    { codigo: "2022032", nombre: "Educación y autismo" },
    { codigo: "2022033", nombre: "Educación y talentos / capacidades excepcionales" },
    { codigo: "2022034", nombre: "Literatura, política y formación" },
    { codigo: "2022035", nombre: "Pensar la ciudad y lo urbano" },
    { codigo: "2022036", nombre: "Temporalidades sociales" },
    { codigo: "2022037", nombre: "La escritura como experiencia formativa en la educación superior" },
    { codigo: "2022038", nombre: "Literatura y diversidad cultural" },
    { codigo: "2022039", nombre: "Literatura comparada: cine, música y pintura" },
    { codigo: "2022040", nombre: "Proyecto de literatura infantil y juvenil" },
    { codigo: "2022042", nombre: "Matemática elemental desde un punto de vista superior: historia y aplicación" },
    { codigo: "2022043", nombre: "Educación matemática y perspectiva histórico-cultural de la educación" },
    { codigo: "2022044", nombre: "Introducción a la astronomía contemporánea" },
  ],
};
